"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-29 22:27:39.147582+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oidc_subject", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "analyst", "viewer", name="user_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=False)
    op.create_index(op.f("ix_app_user_oidc_subject"), "app_user", ["oidc_subject"], unique=True)
    op.create_table(
        "engine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "draining", "offline", name="engine_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engine")),
        sa.UniqueConstraint("name", name=op.f("uq_engine_name")),
    )
    op.create_index(op.f("ix_engine_token_hash"), "engine", ["token_hash"], unique=True)
    op.create_table(
        "notification_channel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "email", "webhook", name="notification_channel_type", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "event_filter",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channel")),
        sa.UniqueConstraint("name", name=op.f("uq_notification_channel_name")),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("confluence", "jira", "smb", name="source_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "connection",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("credential_ref", sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_source_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("name", name=op.f("uq_source_name")),
    )
    op.create_table(
        "scan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum("manual", "scheduled", name="scan_trigger", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "discovering",
                "running",
                "completed",
                "partial",
                "failed",
                "cancelled",
                name="scan_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rulepack_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "counts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_scan_source_id_source"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan")),
    )
    op.create_index(op.f("ix_scan_source_id"), "scan", ["source_id"], unique=False)
    op.create_index(
        "uq_scan_active_per_source",
        "scan",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('discovering', 'queued', 'running')"),
        sqlite_where=sa.text("status IN ('discovering', 'queued', 'running')"),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("cron", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_schedule_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule")),
    )
    op.create_index(op.f("ix_schedule_next_run_at"), "schedule", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_schedule_source_id"), "schedule", ["source_id"], unique=False)
    op.create_table(
        "suppression",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "path_glob",
                "fingerprint",
                "rule",
                name="suppression_scope",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("pattern", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_suppression_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_suppression_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppression")),
    )
    op.create_index(
        "ix_suppression_scope_source_id", "suppression", ["scope", "source_id"], unique=False
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("rule_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("rulepack_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "resource_locator",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("redacted_snippet", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("entropy", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "low", "medium", "high", "critical", name="severity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "open",
                "false_positive",
                "accepted_risk",
                "resolved",
                name="finding_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "resolution",
            sa.Enum("manual", "auto", name="finding_resolution", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_seen_scan_id", sa.Uuid(), nullable=False),
        sa.Column("last_seen_scan_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["app_user.id"],
            name=op.f("fk_finding_assignee_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_scan_id"],
            ["scan.id"],
            name=op.f("fk_finding_first_seen_scan_id_scan"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_scan_id"],
            ["scan.id"],
            name=op.f("fk_finding_last_seen_scan_id_scan"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_finding_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
        sa.UniqueConstraint("source_id", "fingerprint", name="uq_finding_source_id_fingerprint"),
    )
    op.create_index(op.f("ix_finding_fingerprint"), "finding", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_finding_rule_id"), "finding", ["rule_id"], unique=False)
    op.create_index(op.f("ix_finding_source_id"), "finding", ["source_id"], unique=False)
    op.create_index("ix_finding_source_id_state", "finding", ["source_id", "state"], unique=False)
    op.create_table(
        "scan_task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("discovery", "fetch", name="scan_task_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "leased",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="scan_task_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("engine_id", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["engine_id"],
            ["engine.id"],
            name=op.f("fk_scan_task_engine_id_engine"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scan.id"], name=op.f("fk_scan_task_scan_id_scan"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_task")),
    )
    op.create_index(op.f("ix_scan_task_scan_id"), "scan_task", ["scan_id"], unique=False)
    op.create_index(
        "ix_scan_task_status_lease_expires_at",
        "scan_task",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "finding_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "state_change",
                "assign",
                "comment",
                "suppressed",
                "reopened",
                name="finding_event_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("from_value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("to_value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
            name=op.f("fk_finding_event_actor_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_finding_event_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_event")),
    )
    op.create_index(
        op.f("ix_finding_event_finding_id"), "finding_event", ["finding_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_finding_event_finding_id"), table_name="finding_event")
    op.drop_table("finding_event")
    op.drop_index("ix_scan_task_status_lease_expires_at", table_name="scan_task")
    op.drop_index(op.f("ix_scan_task_scan_id"), table_name="scan_task")
    op.drop_table("scan_task")
    op.drop_index("ix_finding_source_id_state", table_name="finding")
    op.drop_index(op.f("ix_finding_source_id"), table_name="finding")
    op.drop_index(op.f("ix_finding_rule_id"), table_name="finding")
    op.drop_index(op.f("ix_finding_fingerprint"), table_name="finding")
    op.drop_table("finding")
    op.drop_index("ix_suppression_scope_source_id", table_name="suppression")
    op.drop_table("suppression")
    op.drop_index(op.f("ix_schedule_source_id"), table_name="schedule")
    op.drop_index(op.f("ix_schedule_next_run_at"), table_name="schedule")
    op.drop_table("schedule")
    op.drop_index(
        "uq_scan_active_per_source",
        table_name="scan",
        postgresql_where=sa.text("status IN ('discovering', 'queued', 'running')"),
        sqlite_where=sa.text("status IN ('discovering', 'queued', 'running')"),
    )
    op.drop_index(op.f("ix_scan_source_id"), table_name="scan")
    op.drop_table("scan")
    op.drop_table("source")
    op.drop_table("notification_channel")
    op.drop_index(op.f("ix_engine_token_hash"), table_name="engine")
    op.drop_table("engine")
    op.drop_index(op.f("ix_app_user_oidc_subject"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.drop_table("app_user")
