"""Result idempotency keys and ingest-time finding suppression (#36)

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-29 23:37:00.876595+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.add_column(sa.Column("suppressed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("suppressed_by_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_finding_suppressed_by_id_suppression"),
            "suppression",
            ["suppressed_by_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("scan_task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("result_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True)
        )


def downgrade() -> None:
    with op.batch_alter_table("scan_task", schema=None) as batch_op:
        batch_op.drop_column("result_key")

    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_finding_suppressed_by_id_suppression"), type_="foreignkey"
        )
        batch_op.drop_column("suppressed_by_id")
        batch_op.drop_column("suppressed_at")
