"""Notification delivery outbox

Dispatch (#60) writes its intention to announce a finding in the same transaction
that opens the finding, and sends afterwards from the maintenance loop. That needs
a table: a row per (channel, finding, scan), carrying attempt count, when it next
becomes due, and the error that ended it if it never went out.

The unique constraint is the load-bearing part. Enqueueing is re-run whenever a
stalled scan is re-finalized, so without it the safety sweep would announce the
same secret again every beat.

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-31 07:10:00.000000+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "notification_delivery",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                "failed",
                name="notification_delivery_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        # CASCADE throughout: a delivery record is about a finding, not part of
        # its history, so removing the finding, the channel, or the scan should
        # take the record rather than be blocked by it (contrast finding's own
        # RESTRICT scan references, added in 0004).
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channel.id"],
            name=op.f("fk_notification_delivery_channel_id_notification_channel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_notification_delivery_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan.id"],
            name=op.f("fk_notification_delivery_scan_id_scan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_delivery")),
        # What makes re-enqueueing idempotent, and therefore what stops the
        # stalled-scan sweep re-announcing every secret it re-finalizes.
        sa.UniqueConstraint(
            "channel_id",
            "finding_id",
            "scan_id",
            name="uq_notification_delivery_channel_finding_scan",
        ),
    )
    # The delivery loop's only query: pending rows that are due.
    op.create_index(
        "ix_notification_delivery_status_next_attempt_at",
        "notification_delivery",
        ["status", "next_attempt_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_notification_delivery_status_next_attempt_at",
        table_name="notification_delivery",
    )
    op.drop_table("notification_delivery")
