"""Remediation actions with evidence links (#142, ADR 0011)

One row per containment action on a finding. Content columns are write-once by
contract (`iceberg_core.models.remediation`); verification and retraction are
set-once field groups, which is why the table has no ``updated_at`` — the
trail of changes lives in ``finding_event``/``audit_event``, not in mutable
columns here.

No ``(created_at, id)`` keyset index: the only read is "all actions for one
finding", unpaginated and bounded, served by the ``finding_id`` FK index — a
cascade child's lookup index, same reasoning as 0007's.

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-12 12:00:00.000000+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    op.create_table(
        "remediation_action",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "revoke",
                "rotate",
                "scope_reduce",
                "remove_source",
                "other",
                name="remediation_action_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evidence_links", _JSON, nullable=False),
        sa.Column("guidance_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "verification",
            sa.Enum(
                "unverified",
                "verified",
                name="remediation_verification",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("verified_by_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retracted_by_id", sa.Uuid(), nullable=True),
        sa.Column("retracted_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # CASCADE from the finding: an action is part of the finding's record,
        # and retention already refuses to purge findings whose state matters.
        # SET NULL from users: the record outlives the account that wrote it.
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_remediation_action_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
            name=op.f("fk_remediation_action_actor_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["app_user.id"],
            name=op.f("fk_remediation_action_verified_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retracted_by_id"],
            ["app_user.id"],
            name=op.f("fk_remediation_action_retracted_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remediation_action")),
    )
    op.create_index(
        "ix_remediation_action_finding_id", "remediation_action", ["finding_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_remediation_action_finding_id", table_name="remediation_action")
    op.drop_table("remediation_action")
