"""Scan modes, durable task checkpoints, and per-scope source cursors (#143)

Three groups of columns and one table, all serving one distinction: whether a
scan undertook to read the whole source or only what changed since a watermark.

``scan.mode`` gates reconciliation. Only a full scan's silence about a finding is
evidence the secret is gone; an incremental scan deliberately never looked at
unchanged content, so it must never auto-resolve anything. Defaulted to ``full``
so every scan predating this migration reads as one, which is what it was.

``scan_task.checkpoint`` is the resume position, and ``checkpoint_sequence`` the
monotonic batch counter guarding it. Per task rather than per attempt: a reclaimed
attempt continues the sequence, so the conditional UPDATE that advances it rejects
a duplicate batch, an out-of-order batch, and a stale engine's batch with one
predicate. ``checkpoint_context`` records what the position is valid under, since
resuming into content the current configuration does not cover would report a scan
of the wrong thing.

``source_cursor`` is per (source, scope) rather than per source: scopes complete
independently, so a space whose tasks failed simply does not advance and is
re-read next time. ``minted_by_scan_id`` is RESTRICT for the reason
``finding.first_seen_scan_id`` is (0004): a row claiming a scan as its provenance
must not outlive it silently.

Enum columns are ``native_enum=False`` throughout (VARCHAR + CHECK), per
``iceberg_core.models.base.enum_type``, so adding a value later needs no migration
and takes no table lock.

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-14 12:00:00.000000+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

_SCAN_MODE = ("full", "incremental")
_INVALIDATION_REASON = (
    "no_cursor",
    "source_configuration_changed",
    "rulepack_changed",
    "pepper_rotating",
    "interval_elapsed",
    "connector_unsupported",
    "operator_requested",
    "source_rejected_cursor",
)


def upgrade() -> None:
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mode",
                sa.Enum(*_SCAN_MODE, name="scan_mode", native_enum=False, length=32),
                nullable=False,
                server_default="full",
            )
        )
        batch_op.add_column(
            sa.Column(
                "promoted_from",
                sa.Enum(*_SCAN_MODE, name="scan_promoted_from", native_enum=False, length=32),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "promotion_reason",
                sa.Enum(
                    *_INVALIDATION_REASON,
                    name="cursor_invalidation_reason",
                    native_enum=False,
                    length=32,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("incremental_baseline_at", sa.DateTime(timezone=True), nullable=True)
        )

    with op.batch_alter_table("scan_task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("checkpoint", _JSON, nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.add_column(
            sa.Column("checkpoint_sequence", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("checkpoint_context", _JSON, nullable=False, server_default=sa.text("'{}'"))
        )

    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mode",
                sa.Enum(*_SCAN_MODE, name="schedule_scan_mode", native_enum=False, length=32),
                nullable=False,
                server_default="full",
            )
        )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("full_scan_interval_days", sa.Integer(), nullable=False, server_default="7")
        )

    op.create_table(
        "source_cursor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("position", _JSON, nullable=False),
        sa.Column("rulepack_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("source_configuration_version", sa.DateTime(timezone=True), nullable=True),
        sa.Column("minted_by_scan_id", sa.Uuid(), nullable=False),
        sa.Column("minted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "invalidation_reason",
            sa.Enum(
                *_INVALIDATION_REASON,
                name="source_cursor_invalidation_reason",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["minted_by_scan_id"],
            ["scan.id"],
            name=op.f("fk_source_cursor_minted_by_scan_id_scan"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_source_cursor_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_cursor")),
    )
    with op.batch_alter_table("source_cursor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_cursor_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            "ix_source_cursor_source_id_invalidated_at",
            ["source_id", "invalidated_at"],
            unique=False,
        )
        batch_op.create_index("uq_source_cursor_scope", ["source_id", "scope"], unique=True)


def downgrade() -> None:
    with op.batch_alter_table("source_cursor", schema=None) as batch_op:
        batch_op.drop_index("uq_source_cursor_scope")
        batch_op.drop_index("ix_source_cursor_source_id_invalidated_at")
        batch_op.drop_index(batch_op.f("ix_source_cursor_source_id"))
    op.drop_table("source_cursor")

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("full_scan_interval_days")

    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.drop_column("mode")

    with op.batch_alter_table("scan_task", schema=None) as batch_op:
        batch_op.drop_column("checkpoint_context")
        batch_op.drop_column("checkpoint_sequence")
        batch_op.drop_column("checkpoint")

    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.drop_column("incremental_baseline_at")
        batch_op.drop_column("promotion_reason")
        batch_op.drop_column("promoted_from")
        batch_op.drop_column("mode")
