"""Accountable owners, routing rules, and response targets (#146)

Three new tables and four columns, for one gap: a finding could be triaged
without anybody being answerable for it. ``finding.assignee_id`` has always
existed, but a person is not an owner — people move teams, and a queue keyed on
one is empty the day they do.

``owner_group`` is the durable accountable team. ``routing_rule`` is how a
finding acquires one without anybody typing: ordered, first match wins, every
matcher optional so a catch-all is just a rule with none set. ``priority`` is
deliberately not unique — a unique column makes "put this above that" a dance
around a constraint, and ``(priority, created_at, id)`` is already a total order.

``response_target`` is one row per severity, and this migration seeds all four.
Seeding rather than defaulting in code is the point: the targets in force are
visible in the table an operator edits, so "why is this due Thursday?" is
answered by looking, not by reading source.

``finding.due_at`` is stored rather than derived at read time because targets are
editable — recomputing would let tightening "high" from 72 to 24 hours reach
backwards and declare last month's closed work to have been late. There is no
``overdue`` column for the mirror-image reason: it is ``due_at < now`` on an
actionable finding, and a stored flag is a second truth that drifts whenever
nothing runs.

``source.tags`` are free-form operator labels, matched by routing rules and used
by nothing else. Backfilled to ``[]``, which matches everything a rule can ask
for except a rule that names a tag — so no existing source starts matching a rule
it should not.

Both new ``finding`` indexes serve a queue the console reads on every load:
"what does this team owe?" and "what is late?".

Enum columns are ``native_enum=False`` (VARCHAR + CHECK) per
``iceberg_core.models.base.enum_type``, so the new ``owner``/``due`` event kinds
needed no schema change at all — ``finding_event.kind`` is already VARCHAR.

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-16 00:00:00.000000+00:00
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

_SEVERITY = ("low", "medium", "high", "critical")

#: Mirrors ``iceberg_core.models.ownership.DEFAULT_RESPONSE_TARGET_HOURS``. A
#: fresh deployment gets dates from its first scan rather than after somebody
#: remembers to configure them.
_DEFAULT_TARGET_HOURS: dict[str, int] = {
    "critical": 24,
    "high": 72,
    "medium": 24 * 14,
    "low": 24 * 30,
}


def upgrade() -> None:
    op.create_table(
        "owner_group",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("notification_channel_id", sa.Uuid(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_channel_id"],
            ["notification_channel.id"],
            name=op.f("fk_owner_group_notification_channel_id_notification_channel"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner_group")),
    )
    with op.batch_alter_table("owner_group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_owner_group_name"), ["name"], unique=True)

    op.create_table(
        "routing_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("owner_group_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("rule_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column(
            "min_severity",
            sa.Enum(*_SEVERITY, name="routing_rule_min_severity", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("source_tags", _JSON, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_group_id"],
            ["owner_group.id"],
            name=op.f("fk_routing_rule_owner_group_id_owner_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_routing_rule_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_rule")),
    )
    with op.batch_alter_table("routing_rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_routing_rule_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_routing_rule_priority"), ["priority"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_routing_rule_owner_group_id"), ["owner_group_id"], unique=False
        )
        batch_op.create_index(
            "ix_routing_rule_priority_created_at_id",
            ["priority", "created_at", "id"],
            unique=False,
        )

    response_target = op.create_table(
        "response_target",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(*_SEVERITY, name="response_target_severity", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("hours", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_response_target")),
    )
    with op.batch_alter_table("response_target", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_response_target_severity"), ["severity"], unique=True)

    seeded_at = datetime.now(UTC)
    op.bulk_insert(
        response_target,
        [
            {
                "id": uuid.uuid4(),
                "created_at": seeded_at,
                "updated_at": seeded_at,
                "severity": severity,
                "hours": hours,
            }
            for severity, hours in _DEFAULT_TARGET_HOURS.items()
        ],
    )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tags", _JSON, nullable=False, server_default=sa.text("'[]'"))
        )

    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_group_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("owner_pinned", sa.Boolean(), nullable=False, server_default="false")
        )
        batch_op.add_column(sa.Column("due_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_finding_owner_group_id_owner_group"),
            "owner_group",
            ["owner_group_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(
            "ix_finding_owner_group_id_state", ["owner_group_id", "state"], unique=False
        )
        batch_op.create_index("ix_finding_state_due_at", ["state", "due_at"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_index("ix_finding_state_due_at")
        batch_op.drop_index("ix_finding_owner_group_id_state")
        batch_op.drop_constraint(
            batch_op.f("fk_finding_owner_group_id_owner_group"), type_="foreignkey"
        )
        batch_op.drop_column("due_at")
        batch_op.drop_column("owner_pinned")
        batch_op.drop_column("owner_group_id")

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("tags")

    with op.batch_alter_table("response_target", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_response_target_severity"))
    op.drop_table("response_target")

    with op.batch_alter_table("routing_rule", schema=None) as batch_op:
        batch_op.drop_index("ix_routing_rule_priority_created_at_id")
        batch_op.drop_index(batch_op.f("ix_routing_rule_owner_group_id"))
        batch_op.drop_index(batch_op.f("ix_routing_rule_priority"))
        batch_op.drop_index(batch_op.f("ix_routing_rule_name"))
    op.drop_table("routing_rule")

    with op.batch_alter_table("owner_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_owner_group_name"))
    op.drop_table("owner_group")
