"""Hand a finding to an external workflow, and track what happened (#141)

Two tables serving one requirement: **repeated delivery creates one external work
item.** Both halves of that are constraints rather than checks somebody has to
remember.

``finding_handoff`` is unique on ``(target_id, finding_id)``, so a second
hand-over of the same finding to the same target cannot be inserted no matter how
many times a button is pressed or a retry fires. And ``idempotency_key`` is
unique and never regenerated, so when a request *did* arrive and the reply was
lost, the retry carries the same key the receiver already deduplicated on.

The retry columns are deliberately the same shape as ``notification_delivery``:
the failure modes are identical — a receiver that is down, a timeout, a ceiling
past which giving up is more honest than retrying forever — and a second dialect
for the same idea would be a second one to get subtly wrong.

``requested_by_id`` is SET NULL rather than CASCADE: a handoff outlives the
account that asked for it, and "who sent our finding to that system" has to stay
answerable.

``source.tags`` gains nothing here. Its ``server_default`` moves onto the model,
which is where autogenerate compares — 0014 set it on the column and the model
did not declare it, so the next autogenerate proposed dropping a default the
NOT NULL column needs. Same class of drift 0016 reconciled, caught the same way.

Revision ID: 0017
Revises: 0016
Create Date: 2026-08-16 06:20:00.000000+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # AutoString appears in autogenerated column ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

_TARGET_TYPE = ("webhook",)
_STATUS = ("pending", "delivered", "failed")


def upgrade() -> None:
    op.create_table(
        "handoff_target",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(*_TARGET_TYPE, name="handoff_target_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("config", _JSON, nullable=False),
        sa.Column("event_filter", _JSON, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoff_target")),
        sa.UniqueConstraint("name", name=op.f("uq_handoff_target_name")),
    )

    op.create_table(
        "finding_handoff",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(*_STATUS, name="handoff_status", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("external_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_finding_handoff_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["app_user.id"],
            name=op.f("fk_finding_handoff_requested_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["handoff_target.id"],
            name=op.f("fk_finding_handoff_target_id_handoff_target"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_handoff")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_finding_handoff_idempotency_key")),
        sa.UniqueConstraint(
            "target_id", "finding_id", name="uq_finding_handoff_target_id_finding_id"
        ),
    )
    with op.batch_alter_table("finding_handoff", schema=None) as batch_op:
        batch_op.create_index("ix_finding_handoff_finding_id", ["finding_id"], unique=False)
        batch_op.create_index(
            "ix_finding_handoff_status_next_attempt_at",
            ["status", "next_attempt_at"],
            unique=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("finding_handoff", schema=None) as batch_op:
        batch_op.drop_index("ix_finding_handoff_status_next_attempt_at")
        batch_op.drop_index("ix_finding_handoff_finding_id")
    op.drop_table("finding_handoff")
    op.drop_table("handoff_target")
